### ISSUE TITLE
ModuleNotFoundError: No module named 'ui'

### ISSUE THREAD

**Issue by motoridersd** [zocker-160/thinkfan-ui#1]
Getting that error when running for the first time on Pop/Ubuntu 20.10. I installed the dependencies as listed in the readme

sudo python3 fan.py
Traceback (most recent call last):
  File "fan.py", line 12, in <module>
    from ui.gui import Ui_MainWindow
ModuleNotFoundError: No module named 'ui'

**Comment by zocker-160** [comment]
did you clone the repository?

the `fan.py` file alone is not enough, it needs the files inside the ui folder too

**Comment by zocker-160** [comment]
I know the readme is lacking that information, I am sorry about that.

But with the ui folder next to the fan.py, it should work.

**Comment by motoridersd** [comment]
I did not. I cloned it and now it works. Yeah, maybe adding that to the readme would be useful :P I assumed fan.py was all that was needed.

**Comment by zocker-160** [comment]
yes I will update the readme, thank you for brinding this up

**Comment by motoridersd** [comment]
You're welcome! And thank you for this. I was just looking into a GUI for thinkfan today, and your reddit posts popped up

**Comment by zocker-160** [comment]
glad to hear :+1:  Hope it is useful for you, it is pretty new, so bugs are likely :D

**Comment by zocker-160** [comment]
A `.deb` package is now available for easier install on Debian / Ubuntu systems ;)
