### ISSUE TITLE
The app has no icon (so uses default icon) on KDE Wayland taskbar

### ISSUE THREAD

**Issue by Markedo** [zocker-160/thinkfan-ui#11]
Dear zocker-160, thanks for this nice project! I really like it!

Here is the little issue I've been seeing for a long time: the app uses the default Wayland icon on KDE in the taskbar and window title (screenshot attached). On the other hand, the icons in tray and in application launcher are correct.

I've installed this app using arch AUR https://aur.archlinux.org/packages/thinkfan-ui

Here is my current setup.
OS: EndeavourOS
Kernel: 6.5.2-zen1-1-zen
DE: Plasma 5.27.7 Wayland
WM: kwin

If you need any other information or assistance in testing, please don't hesitate to contact me, I'll be happy to help.

![Screenshot_20230911_144449](https://github.com/zocker-160/thinkfan-ui/assets/83120132/1d075753-12cb-4370-b9f9-cfa06880eabd)

**Comment by zocker-160** [comment]
thank you for reporting
