### ISSUE TITLE
I can run more than one program

### ISSUE THREAD

**Issue by JBLHRD** [zocker-160/thinkfan-ui#12]
When I close the application window, it doesn't close, but collapses to the system tray. And this is correct. 

However, when you start the application again, a new process will be opened, with a separate icon in the system tray. Although, it would be logical to just call the existing process. Can you fix it?

![зображення](https://github.com/zocker-160/thinkfan-ui/assets/147275844/20c379ab-9169-4979-9233-7fdc79ad948e)

**Comment by zocker-160** [comment]
Yep this is true, currently there is no check if an instance is already running.

I will fix it.
