### ISSUE TITLE
When restarted it said i need to put this in conf options thinkpad_acpi fan_control=1

### ISSUE THREAD

**Issue by TUX-A1CUA0** [zocker-160/thinkfan-ui#15]
Any possible solution for this

**Comment by zocker-160** [comment]
This application needs access to `/proc/acpi/ibm/fan`. 
Your kernel has to have `thinkpad-acpi` patch included, otherwise that does not exist and this application will not work.

**Comment by TUX-A1CUA0** [comment]
![Screenshot_20241117_000226](https://github.com/user-attachments/assets/5cb26e3d-b104-4a26-8461-49d57048ba0a)

**Comment by TUX-A1CUA0** [comment]
but it works when i first installed it

**Comment by TUX-A1CUA0** [comment]
> This application needs access to `/proc/acpi/ibm/fan`. Your kernel has to have `thinkpad-acpi` module loaded otherwise that does not exist and this application will not work.

but it works when i first installed it

**Comment by zocker-160** [comment]
The required kernel module is probably not loaded, after installation it does force load it, which is probably why it worked at first.

you can check using `lsmod | grep acpi`

**Comment by zocker-160** [comment]
if it is not loaded you can manually load it using `modprobe thinkpad_acpi`

**Comment by TUX-A1CUA0** [comment]
> The required kernel module is probably not loaded, after installation it does force load it, which is probably why it worked at first.
> 
> you can check using `lsmod | grep acpi`

![Screenshot_20241117_000834](https://github.com/user-attachments/assets/910193b0-e27b-4331-bd86-596b635115c0)

heres the result it seems not loaded with

**Comment by TUX-A1CUA0** [comment]
![Screenshot_20241117_001046](https://github.com/user-attachments/assets/f80ca7b8-55cd-4d96-a844-44255dd28377)

still the same even i put modprobe thinkpad_acpi

**Comment by zocker-160** [comment]
does it work after a reinstall?

**Comment by TUX-A1CUA0** [comment]
> does it work after a reinstall?

it work when reinstall but when restart it just throw an error i

**Comment by zocker-160** [comment]
Does it work if you reload the kernel module using
```
modprobe -r thinkpad_acpi
modprobe thinkpad_acpi
```

**Comment by TUX-A1CUA0** [comment]
> Does it work if you reload the kernel module using
> 
> ```
> modprobe -r thinkpad_acpi
> modprobe thinkpad_acpi
> ```

do i need to remove it

**Comment by zocker-160** [comment]
you don't, you just run the two commands with sudo, it unloads and reloads the module

**Comment by TUX-A1CUA0** [comment]
modprobe: ERROR: could not remove 'thinkpad_acpi': Operation not permitted

**Comment by zocker-160** [comment]
you get this as superuser?

**Comment by TUX-A1CUA0** [comment]
it work but let me try when i restart it

**Comment by TUX-A1CUA0** [comment]
still the same problem when restarted

**Comment by zocker-160** [comment]
Ok alright, the problem is that the kernel modules are not getting properly loaded when you restart. 

Sadly I don't think there is anything I can do here to help you as this is not an application problem.

**Comment by TUX-A1CUA0** [comment]
Thank you anyway goodapplication btw very helpful to my steamy t420 now that i ifnd the rootcause

**Comment by Boranstars** [comment]
> Thank you anyway goodapplication btw very helpful to my steamy t420 now that i ifnd the rootcause

I have the same issue with you and I use X1Carbon2018 btw.How did you fix it?
